name: flext_core
description: Flext extensions for dart and flutter.
version: 0.3.0
homepage: https://github.com/gianmarcocalbi/flext/tree/main/packages/flext_core

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: {}
