name: flext_go_router
description: Flext extension for go_router.
version: 0.1.0
homepage: https://github.com/gianmarcocalbi/flext/tree/main/packages/flext_go_router

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
