include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    invalid_use_of_visible_for_testing_member: error
    invalid_use_of_protected_member: error
    invalid_override_of_non_virtual_member: error

linter:
  rules:
    prefer_relative_imports: true
    lines_longer_than_80_chars: true
    avoid_print: true
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    use_named_constants: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: false
    await_only_futures: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    avoid_unused_constructor_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    unrelated_type_equality_checks: true
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    prefer_function_declarations_over_variables: false
