import 'package:flutter/material.dart';

extension FlextCoreIconButton on IconButton {
  IconButton copyWith({
    AlignmentGeometry? alignment,
    bool? autofocus,
    bool? enableFeedback,
    bool? isSelected,
    BoxConstraints? constraints,
    ButtonStyle? style,
    Color? color,
    Color? disabledColor,
    Color? focusColor,
    Color? highlightColor,
    Color? hoverColor,
    Color? splashColor,
    double? iconSize,
    double? splashRadius,
    EdgeInsetsGeometry? padding,
    FocusNode? focusNode,
    Key? key,
    MouseCursor? mouseCursor,
    String? tooltip,
    VisualDensity? visualDensity,
    VoidCallback? onPressed,
    Widget? icon,
    Widget? selectedIcon,
  }) {
    return IconButton(
      alignment: alignment ?? this.alignment,
      autofocus: autofocus ?? this.autofocus,
      color: color ?? this.color,
      constraints: constraints ?? this.constraints,
      disabledColor: disabledColor ?? this.disabledColor,
      enableFeedback: enableFeedback ?? this.enableFeedback,
      focusColor: focusColor ?? this.focusColor,
      focusNode: focusNode ?? this.focusNode,
      highlightColor: highlightColor ?? this.highlightColor,
      hoverColor: hoverColor ?? this.hoverColor,
      icon: icon ?? this.icon,
      iconSize: iconSize ?? this.iconSize,
      isSelected: isSelected ?? this.isSelected,
      key: key ?? this.key,
      mouseCursor: mouseCursor ?? this.mouseCursor,
      onPressed: onPressed ?? this.onPressed,
      padding: padding ?? this.padding,
      selectedIcon: selectedIcon ?? this.selectedIcon,
      splashColor: splashColor ?? this.splashColor,
      splashRadius: splashRadius ?? this.splashRadius,
      style: style ?? this.style,
      tooltip: tooltip ?? this.tooltip,
      visualDensity: visualDensity ?? this.visualDensity,
    );
  }
}
