name: flext
description: All Flext extensions for Flutter.
version: 1.4.1
homepage: https://github.com/gianmarcocalbi/flext/tree/main/packages/flext

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flext_core: ^0.5.0+1
  flext_bloc: ^0.1.0
  flext_go_router: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
